name: ChatRingtone
version: '${project.version}'
main: hibikero.chatringtone.ChatRingtone
api-version: '1.20'

commands:
  sdpurchase:
    permission: ""
  sdsetfor:
    permission: ""
  sdmodesetfordef:
    permission: ""
  sdmodesetformut:
    permission: ""
  vcpanel:
    permission: ""